project_id = "ynuggqeumqzwwuffrnnv"

[functions.fetch-pubmed]
verify_jwt = false

[functions.update-trials]
verify_jwt = false

[functions.generate-analysis]
verify_jwt = false

[functions.generate-patient-pdf]
verify_jwt = false

[functions.seed-trial-data]
verify_jwt = false

[functions.fetch-trial-results]
verify_jwt = false

[functions.fetch-pubmed-data]
verify_jwt = false

[functions.fetch-ctgov-data]
verify_jwt = false

[functions.manage-users]
verify_jwt = false

[functions.login-with-username]
verify_jwt = false

[functions.generate-drug-patient-info]
verify_jwt = false

[functions.search-regimens]
verify_jwt = false